const wrestlers = [

    {name: "Adam Cole",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "AJ Styles",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Alberto del Rio",
        image: "images/Vacante.jpg",
        nickname: "El Patron",
        stable: "",
        division: "NXT",
        brand: "NXT",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "active",
        achievements: []
    },
{name: "Aleister Black",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Andrade",image: "images/zacarias.jpg", nickname: "El Idolo", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Axiom",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "Club de amigos",
        division: "Monday Night RAW",
        brand: "RAW",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "active",
        achievements: []
    },

    {name: "Austin Theory",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

{name: "Batista",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

{name: "Bobby Lashley",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Bo Dallas",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name: "Bravo Americano",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name:"Bray Wyatt",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {
        name: "Bret Hart",
        image: "images/Darkman Hart.jpg",
        nickname: "The Darkman",
        stable: "Hart ReFoundation",
        division: "Main Roster",
        brand: "RAW",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "active",

        achievements: [
            "16x World Champion",
            "5x United States Champion"
        ]},

    {name: "Brock Lesnar",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Bron Breakker",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
           
{name: "Bryan Danielson",image: "images/Vacante.jpg", nickname: "", stable: "Blackpool Combat Club",
      division: "Monday Night RAW",  brand: "RAW",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0",  status: "active",achievements: []},

    {name: "Buddy Matthews",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name: "Chad Gable",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
        
{name: "Charlie Dempsey",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "",
        division: "Friday Night Smackdown",
        brand: "SmackDown",
        overall2026: "10 - 0 - 10",
        careerOverall: "0 - 10 - 0",
        status: "active",
        achievements: []},
    
    {name: "Chris Benoit",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name: "Chris Jericho",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Claudio Castagnoli",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "CM Punk",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
    
    {
        name: "Cody Rhodes",
        image: "images/Cody Rhodes trivias.jpg",
        nickname: "The American Nightmare",
        stable: "",
        division: "Main Roster",
        brand: "RAW",
        overall2026: "0 - 0",
        careerOverall: "0 - 0",
        status: "active",

        achievements: [
            "2x WWE Undisputed Champion",
            "2x TNA Champion",
            "Royal Rumble Winner 2024"
        ]},
      
{name: "Christian Cage",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "Friday Night Smackdown",  brand: "SmackDown",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0",  status: "active",achievements: []},

{name: "Dezmond Xavier",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
    
{name: "Damian Priest",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name: "Dominik Mysterio",image: "images/zacarias.jpg", nickname: "El Sucio", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Dragon Lee",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Drew McIntyre",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Eddie Guerrero",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
{name: "Edge",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
 {name: "El Grande Americano",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    {name: "Enzo Amore",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Ethan Page",image: "images/zacarias.jpg", nickname: "All Ego", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Finn Balor",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "",
        division: "Friday Night Smackdown",
        brand: "SmackDown",
        overall2026: "10 - 0 - 10",
        careerOverall: "0 - 10 - 0",
        status: "active",
        achievements: []},

    {name: "GUNTHER",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Ilja Dragunov",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Jacob Fatu",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "Monday Night RAW",  brand: "RAW",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0",  status: "active",achievements: []},

    {name: "JD Mcdonagh",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    { name: "Jeff Jarrett",
        image: "images/Jeff Jarrett trivias.jpg",
        nickname: "The Chosen One",
        stable: "",
        division: "",
        brand: "",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "inactive",
        achievements: [
            "x5 WWE Undisputed Champion"
        ]},

    {name: "Jeff Hardy",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Je'Von Evans",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Jey Uso",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Jimmy Uso",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},

    
    {name: "Joe Hendry",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "John Cena",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Johnny Gargano",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
     {name: "Jon Moxley",image: "images/Vacante.jpg", nickname: "", stable: "Blackpool Combat Club",
      division: "Monday Night RAW",  brand: "RAW",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0",  status: "active",achievements: []},


    {name: "Kane",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
{name: "Karrion Kross",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
    {name: "Keith Lee",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Kenny Omega",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Kevin Owens",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Kofi Kingston",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Kyle O'Reilly",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "",
        division: "Friday Night Smackdown",
        brand: "SmackDown",
        overall2026: "10 - 0 - 10",
        careerOverall: "0 - 10 - 0",
        status: "active",
        achievements: []},

    {name: "LA Knight",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "",
        division: "Friday Night Smackdown",
        brand: "SmackDown",
        overall2026: "10 - 0 - 10",
        careerOverall: "0 - 10 - 0",
        status: "active",
        achievements: []},

    {name: "Leon Slater",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Logan Paul",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Ludwig Kaiser",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Matt Cardona",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "MJF",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Nathan Frazer",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
    {name: "Nic Nemeth",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
{name: "Owen Hart",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Original Grande Americano",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "PAC",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    
     {name: "Randy Orton",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "",
        division: "Friday Night Smackdown",
        brand: "SmackDown",
        overall2026: "10 - 0 - 10",
        careerOverall: "0 - 10 - 0",
        status: "active",
        achievements: ["Intercontinental championship (current)"]},
{name: "Penta",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Pete Dunne",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "R-Truth",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Rey Fenix",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Rey Mysterio",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "RICOCHET",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Rob Van Dam",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Roderick Strong",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Roman Reigns",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

    {name: "Sami Zayn",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Shawn Michaels",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Shinsuke Nakamura",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Sin Cara",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Solo Sikoa",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

     
    
    {        name: "Seth Rollins",
        image: "images/Seth Rollins trivias.jpg",
        nickname: "",
        stable: "The Vision",
        division: "Main Roster",
        brand: "SmackDown",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "active",

        achievements: [
            "16x World Champion",
            "5x United States Champion"
        ]},
    
   
    {
        name: "Shawn Spears",
        image: "images/shawna spears.jpg",
        nickname: "",
        stable: "",
        division: "RAW",
        brand: "RAW",
        overall2026: "0 - 0 - 100",
        careerOverall: "0 - 0",
        status: "active",

        achievements:[ ]
        
    },

    {name: "Sheamus",image: "images/Vacante.jpg", nickname: "", stable: "",
      division: "NXT",  brand: "NXT",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
    
     {name: "Swerve Strickland",image: "images/Vacante.jpg", nickname: "", stable: "", 
      division: "Friday Night Smackdown",  brand: "SmackDown",overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
      status: "active",achievements: []},

    {name: "Tama Tonga",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Ted Dibiase Jr",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "The Miz",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "The Rock",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "The Sandman",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "The Undertaker",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Timothy Thatcher",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Tommaso Ciampa",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Tonga Loa",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
{name: "Trick Williams",image: "images/Trick Williams trivias.jpg", nickname: "", stable: "",
      division: "Monday Night RAW",  brand: "RAW",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "active",achievements: []},
    {name: "Tyler Bate",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Velveteen Dream",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},
    {name: "Wade Barrett",image: "images/zacarias.jpg", nickname: "", stable: "",
      division: "",  brand: "",
      overall2026: "10 - 0 - 10", careerOverall: "0 - 10 - 0", 
 status: "inactive",achievements: []},

{name: "Vacante",
        image: "images/Vacante.jpg",
        nickname: "",
        stable: "Club de amigos",
        division: "NXT",
        brand: "NXT",
        overall2026: "100 - 0",
        careerOverall: "0 - 0",
        status: "active",
        achievements: ["16x World Champion of panchos","5x United States Champion" ]},
    
];



