const urlParams=new URLSearchParams(window.location.search),tournamentId=urlParams.get("id"),tournaments=[];
for(let number=25;number>=1;number--){tournaments.push({id:`raw-${number}`,number,brand:"RAW",division:"FIRST DIVISION",title:`TOURNAMENT ${number}`});tournaments.push({id:`smackdown-${number}`,number,brand:"SMACKDOWN",division:"FIRST DIVISION",title:`TOURNAMENT ${number}`})}
for(let number=18;number>=1;number--)tournaments.push({id:`nxt-${number}`,number,brand:"NXT",division:"SECOND DIVISION",title:`TOURNAMENT ${number}`});
const specialChampionships={"campeonato-1":{brand:"CHAMPIONSHIP 1",title:"CHAMPIONSHIP 1",division:"LEAGUE / PLAY-IN / ELIMINATION CHAMBER"},"campeonato-2":{brand:"CHAMPIONSHIP 2",title:"CHAMPIONSHIP 2",division:"RAW / SMACKDOWN / WRESTLEMANIA"},"campeonato-3":{brand:"CHAMPIONSHIP 3",title:"CHAMPIONSHIP 3",division:"LEAGUE / BACKLASH"},"campeonato-4":{brand:"CHAMPIONSHIP 4",title:"CHAMPIONSHIP 4",division:"RAW / SMACKDOWN / NXT / NIGHT OF CHAMPIONS"}};
const tournament=tournaments.find(item=>item.id===tournamentId),special=specialChampionships[tournamentId],tournamentBrand=document.getElementById("tournament-brand"),tournamentTitle=document.getElementById("tournament-title"),tournamentDivision=document.getElementById("tournament-division"),draftContainer=document.getElementById("draft-container"),standingsBody=document.getElementById("standings-body"),matrixTable=document.getElementById("matrix-table"),resultsContainer=document.getElementById("results-container");
function createWrestlerId(name){return name.toLowerCase().trim().replace(/\s+/g,"-")}
function normalizeName(name){return name.toLowerCase().trim()}
function getWrestler(name){if(typeof wrestlers==="undefined")return null;return wrestlers.find(w=>normalizeName(w.name)===normalizeName(name))||null}
function getWrestlerImage(name){const data=tournamentData[tournamentId],image=data?.images?.[name];if(image)return image;const wrestler=getWrestler(name);return wrestler?.image||"images/Vacante.jpg"}
function createWrestlerLink(name){return `<a href="superstar.html?id=${createWrestlerId(name)}" class="table-wrestler-link">${name}</a>`}
function clearSections(){draftContainer.innerHTML="";standingsBody.innerHTML="";matrixTable.innerHTML="";resultsContainer.innerHTML=""}
function showComingSoon(){draftContainer.innerHTML="<p>PARTICIPANTS COMING SOON</p>";standingsBody.innerHTML=`<tr><td colspan="7">STANDINGS COMING SOON</td></tr>`;matrixTable.innerHTML="<tr><td>MATRIX COMING SOON</td></tr>";resultsContainer.innerHTML="<p>RESULTS COMING SOON</p>"}
function renderDraft(participants){draftContainer.innerHTML="";if(!participants.length){draftContainer.innerHTML="<p>NO PARTICIPANTS</p>";return}participants.forEach(name=>{const card=document.createElement("div");card.className="draft-card";card.innerHTML=`<a href="superstar.html?id=${createWrestlerId(name)}" style="text-decoration:none;color:inherit;"><img src="${getWrestlerImage(name)}" alt="${name}" class="draft-card-image"><span class="draft-card-name">${name}</span></a>`;draftContainer.appendChild(card)})}
function buildStandings(participants,matches){const standings={};participants.forEach(name=>standings[name]={name,played:0,wins:0,draws:0,losses:0,points:0,scoreFor:0,scoreAgainst:0});matches.forEach(match=>{const a=standings[match.wrestler1],b=standings[match.wrestler2];if(!a||!b)return;a.played++;b.played++;a.scoreFor+=Number(match.score1);a.scoreAgainst+=Number(match.score2);b.scoreFor+=Number(match.score2);b.scoreAgainst+=Number(match.score1);if(match.score1>match.score2){a.wins++;a.points+=3;b.losses++}else if(match.score1<match.score2){b.wins++;b.points+=3;a.losses++}else{a.draws++;b.draws++;a.points++;b.points++}});return Object.values(standings).sort((a,b)=>b.points-a.points||b.wins-a.wins||(b.scoreFor-b.scoreAgainst)-(a.scoreFor-a.scoreAgainst))}
function renderStandings(participants,matches){const list=buildStandings(participants,matches);standingsBody.innerHTML="";if(!list.length){standingsBody.innerHTML=`<tr><td colspan="7">NO STANDINGS</td></tr>`;return}list.forEach((w,index)=>{const row=document.createElement("tr");row.innerHTML=`<td>${index+1}</td><td>${createWrestlerLink(w.name)}</td><td>${w.played}</td><td>${w.wins}</td><td>${w.draws}</td><td>${w.losses}</td><td>${w.points}</td>`;if(index===0)row.classList.add("champion");if(index===list.length-1)row.classList.add("relegation");standingsBody.appendChild(row)})}
function renderMatrix(participants,matches){matrixTable.innerHTML="";if(!participants.length){matrixTable.innerHTML="<tr><td>MATRIX COMING SOON</td></tr>";return}const header=document.createElement("tr");header.innerHTML="<th>WRESTLER</th>";participants.forEach(name=>{const th=document.createElement("th");th.textContent=name;header.appendChild(th)});matrixTable.appendChild(header);participants.forEach(name=>{const row=document.createElement("tr"),nameCell=document.createElement("td");nameCell.innerHTML=createWrestlerLink(name);row.appendChild(nameCell);participants.forEach(opponent=>{const cell=document.createElement("td");if(name===opponent){cell.textContent="—";row.appendChild(cell);return}const match=matches.find(m=>(m.wrestler1===name&&m.wrestler2===opponent)||(m.wrestler1===opponent&&m.wrestler2===name));if(!match){cell.textContent="·";cell.classList.add("matrix-empty")}else if(match.score1===match.score2){cell.textContent="D";cell.classList.add("matrix-draw")}else{const first=match.wrestler1===name,won=first?match.score1>match.score2:match.score2>match.score1;cell.textContent=won?"W":"L";cell.classList.add(won?"matrix-win":"matrix-loss")}row.appendChild(cell)});matrixTable.appendChild(row)})}
function renderResults(matches,phases){resultsContainer.innerHTML="";if(!matches.length){resultsContainer.innerHTML="<p>NO RESULTS</p>";return}const grouped={};matches.forEach(match=>{const date=match.date??"OTHER";if(!grouped[date])grouped[date]=[];grouped[date].push(match)});Object.keys(grouped).sort((a,b)=>{const na=parseInt(a),nb=parseInt(b);return!isNaN(na)&&!isNaN(nb)?na-nb:String(a).localeCompare(String(b))}).forEach(date=>{const title=document.createElement("div");title.className="results-date";title.textContent=phases&&phases[date-1]?phases[date-1]:date==="OTHER"?"OTHER":`DATE ${date}`;resultsContainer.appendChild(title);grouped[date].forEach(match=>{const result=document.createElement("div");result.className="result-card";result.classList.add(match.score1>match.score2?"wrestler1-win":match.score1<match.score2?"wrestler2-win":"draw");result.innerHTML=`<div class="result-wrestler">${createWrestlerLink(match.wrestler1)}</div><div class="result-score">${match.score1} - ${match.score2}</div><div class="result-wrestler">${createWrestlerLink(match.wrestler2)}</div>`;resultsContainer.appendChild(result)})})}
function getEventMatches(data){const events=data.events||{};const ids=Array.isArray(events)?events:Object.values(events);return ids.flatMap(id=>(typeof eventData!=="undefined"?eventData[id]?.results||[]:[])).filter(m=>m.wrestler1&&m.wrestler2&&m.score1!==undefined&&m.score2!==undefined)}
function renderChamberBracket(matches,container){const chamberMatches=matches.filter(m=>m.wrestler1&&m.wrestler2&&m.score1!==undefined&&m.score2!==undefined);const heading=document.createElement("div");heading.className="results-date";heading.textContent="ELIMINATION CHAMBER";container.appendChild(heading);if(!chamberMatches.length){const p=document.createElement("p");p.textContent="BRACKET COMING SOON";container.appendChild(p);return}const bracket=document.createElement("div");bracket.className="chamber-bracket";[{title:"QUARTERFINALS",matches:chamberMatches.slice(0,4)},{title:"SEMIFINALS",matches:chamberMatches.slice(4,6)},{title:"FINAL",matches:chamberMatches.slice(6,7)}].forEach(round=>{const column=document.createElement("div");column.className="bracket-round";const title=document.createElement("h3");title.textContent=round.title;column.appendChild(title);round.matches.forEach(match=>{const card=document.createElement("div");card.className="bracket-match";const winner1=match.score1>match.score2,winner2=match.score2>match.score1;card.innerHTML=`<div class="${winner1?"winner":""}">${createWrestlerLink(match.wrestler1)}<span>${match.score1}</span></div><div class="${winner2?"winner":""}">${createWrestlerLink(match.wrestler2)}<span>${match.score2}</span></div>`;column.appendChild(card)});bracket.appendChild(column)});container.appendChild(bracket)}
function renderPhase(title,matches){if(!matches.length)return;const section=document.createElement("div");section.className="championship-phase";section.innerHTML=`<div class="results-date">${title}</div>`;matches.forEach(match=>{const card=document.createElement("div");card.className="result-card";card.classList.add(match.score1>match.score2?"wrestler1-win":match.score1<match.score2?"wrestler2-win":"draw");card.innerHTML=`<div class="result-wrestler">${createWrestlerLink(match.wrestler1)}</div><div class="result-score">${match.score1} - ${match.score2}</div><div class="result-wrestler">${createWrestlerLink(match.wrestler2)}</div>`;section.appendChild(card)});resultsContainer.appendChild(section)}
function renderNormalTournament(data){const participants=data.participants||[],matches=data.matches||[];renderDraft(participants);renderStandings(participants,matches);renderMatrix(participants,matches);renderResults(matches)}
function renderChampionship1(data){const participants=data.participants||[],events=data.events||{};renderDraft(participants);standingsBody.innerHTML=`<tr><td colspan="7">LEAGUE STANDINGS COMING SOON</td></tr>`;matrixTable.innerHTML="<tr><td>MATCH MATRIX COMING SOON</td></tr>";resultsContainer.innerHTML="";renderChamberBracket(eventData?.[events.BRACKET]?.results||[],resultsContainer);renderPhase("PLAY-IN",eventData?.[events["PLAY-IN"]]?.results||[]);["LIVE 1","LIVE 2","LIVE 3","LIVE 4","LIVE 5"].forEach(key=>renderPhase(key,eventData?.[events[key]]?.results||[]))}
function renderChampionship2(data){const zones=data.zones||{},participants=[...(zones.RAW||[]),...(zones.SMACKDOWN||[])];renderDraft(participants);if(data.matches?.length){renderStandings(participants,data.matches);renderMatrix(participants,data.matches);renderResults(data.matches,data.phases)}else{standingsBody.innerHTML=`<tr><td colspan="7">STANDINGS COMING SOON</td></tr>`;matrixTable.innerHTML="<tr><td>MATRIX COMING SOON</td></tr>";resultsContainer.innerHTML="<p>RESULTS COMING SOON</p>"}}
function renderChampionship3(data){const participants=data.participants||[],matches=data.matches||[];renderDraft(participants);if(matches.length){renderStandings(participants,matches);renderMatrix(participants,matches);renderResults(matches,data.phases)}else{standingsBody.innerHTML=`<tr><td colspan="7">STANDINGS COMING SOON</td></tr>`;matrixTable.innerHTML="<tr><td>MATRIX COMING SOON</td></tr>";resultsContainer.innerHTML="<p>RESULTS COMING SOON</p>"}}
function renderChampionship4(data){const zones=data.zones||{},participants=[...(zones.RAW||[]),...(zones.SMACKDOWN||[]),...(zones["NXT A"]||[]),...(zones["NXT B"]||[])];renderDraft(participants);if(data.matches?.length){renderStandings(participants,data.matches);renderMatrix(participants,data.matches);renderResults(data.matches,data.phases)}else{standingsBody.innerHTML=`<tr><td colspan="7">STANDINGS COMING SOON</td></tr>`;matrixTable.innerHTML="<tr><td>MATRIX COMING SOON</td></tr>";resultsContainer.innerHTML="<p>RESULTS COMING SOON</p>"}}
if(special){tournamentBrand.textContent=special.brand;tournamentTitle.textContent=special.title;tournamentDivision.textContent=special.division;const page=document.querySelector(".torneoroad-page");if(page)page.classList.add("championship");const currentData=tournamentData[tournamentId];clearSections();if(currentData){if(currentData.format==="LEAGUE_PLAYIN_ELIMINATION")renderChampionship1(currentData);else if(currentData.format==="TWO_ZONES_ELIMINATION")renderChampionship2(currentData);else if(currentData.format==="LEAGUE_ELIMINATION")renderChampionship3(currentData);else if(currentData.format==="FOUR_ZONES_ELIMINATION")renderChampionship4(currentData);else showComingSoon()}else showComingSoon()}else if(!tournament){tournamentBrand.textContent="";tournamentTitle.textContent="TOURNAMENT NOT FOUND";tournamentDivision.textContent="";showComingSoon()}else{tournamentBrand.textContent=tournament.brand;tournamentTitle.textContent=tournament.title;tournamentDivision.textContent=tournament.division;const page=document.querySelector(".torneoroad-page");if(page)page.classList.add(tournament.brand.toLowerCase());const currentData=tournamentData[tournamentId];if(!currentData)showComingSoon();else renderNormalTournament(currentData)}
